---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    label: Cortex

- glances:
    url: http://192.168.1.2:61208
    cpu: true
    mem: true
    disk: /
    label: Raspberry Pi
    version: 4

- glances:
    url: http://192.168.1.5:61208
    cpu: true
    mem: true
    disk: /volume1
    label: Synology
    version: 4

- search:
    provider: duckduckgo
    target: _blank
